dist: trusty
sudo: false
language: cpp
branches:
  only:
    - master
env:
- DOCKERFILE=Dockerfile CACHE=latest SCRIPT=src/scripts/coverage.sh
- DOCKERFILE=Dockerfile.nop11 CACHE=latest SCRIPT=src/scripts/test.sh
- DOCKERFILE=Dockerfile.deb-stable CACHE=latest-deb-stable SCRIPT=src/scripts/test.sh
  DARGS="-eBUILD_ONLY=1 -eBUILD_DEB=1"
- DOCKERFILE=Dockerfile.deb-unstable CACHE=latest-deb-unstable SCRIPT=src/scripts/test.sh
  DARGS="-eBUILD_ONLY=1"
- DOCKERFILE=Dockerfile.gcc4 CACHE=latest SCRIPT=src/scripts/test.sh DARGS="-eBUILD_ONLY=1"
services:
- docker
script:
- docker pull advancedtelematic/aktualizr:$CACHE
- docker build --cache-from advancedtelematic/aktualizr:$CACHE -t advancedtelematic/aktualizr
  -f ${DOCKERFILE} .
- ci_env=`bash <(curl -s https://codecov.io/env)`
- docker run -v /persistent:/persistent $ci_env $DARGS --name "$CACHE" -it advancedtelematic/aktualizr
  ${SCRIPT}
- "./scripts/test_deb_in_docker.sh ${DOCKERFILE}"
deploy:
  provider: releases
  file: /persistent/garage_deploy.deb
  skip-cleanup: true
  api_key:
    secure: r0cU39a/s+cH8SljOiBCuRyZYGCoDAyf54dKUGtnJKPG+7bVdt4V9tqUofG/IG9lje70F28XrYO6PCoaeSrd0/VWDlpzRJo40wV+hcNSKLfgAnITL9dOOE1kcwQx/QqKlLX7IOfxhb7neMUI/FFCrOdqNkO6R7lDAq9rluBcI+GcMhB7IPH+AGVnxxSCDHQoG70TT2DEnbetpXE7U3PYROOYABB2+9AGxHev2KVK7hnpqjBl7XlzbxauCYs5mD1r08GIkYXDO/52xDgZHItFZGgZBKy8hBeLCzAZf0JMoHOIiXFzEHHvSwezZrE1+ejfIcWL3puSbydb0qgt8keZFQvDXkC9DIlAfAborkFIXqlZMH+1gf6s9ONMeFDSxMsPBWRpVWBBLvmmB+uEziE/lcY8zQ2IefcYCpSJNZVy95IYJ89c9051baKe5qYqS91B2tcd0Kx+pHPjMQa2+WiB9lmNcjo22Lw5aGHHdMa/TgWKz7u3yitUOY+5/oLmTZdhi6Y0Rb5x6vvOWUoQPS52wqicgPR/dBbOY5DUp4DsCf1Ej5fj10omG3HKwJJjaC3ERUBgT1ojQNpfNDyUKe8vRodtrhVd1NhZQCJXCZWyn9mV7Ic47Gh+qqIZQWN2NbA5lcKQUwnS2MEkp2Z4n57lAWueOXfthLJaEzL7jNL6iz8=
  on:
    tags: true
    repo: advancedtelematic/aktualizr
    condition: $DOCKERFILE = Dockerfile.deb-stable
